name: WVS_School_Class_Service
description: Service for the school classes of the Werner-von-Siemens school Frankfurt(Main)
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  shelf: ^0.7.5
  html: 0.14.0+3
  http: 0.12.0+4

dev_dependencies:
  pedantic: ^1.9.0
